comidas/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.ingresar, name='ingresar'),
    path('productos_list', views.productos_list, name='productos_list'),
    path('pedidos_list', views.pedidos_list, name='pedidos_list'),
    path('pedidos/new', views.pedido_new, name='pedido_new'),
    path('come_part', views.come_part, name='come_part'),
    path('come_prod', views.come_prod, name='come_prod'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comidas.urls')),
]

comidas/models.py
from django.db import models
from django.utils import timezone

# Modelo Participantes
class Participantes(models.Model):
    id_part = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return self.first_name

# Modelo Productos
class Productos(models.Model):
    id_prod = models.AutoField(primary_key=True)
    name_prod = models.CharField(max_length=70)
    desc_prod = models.CharField(max_length=250)
    cantidad = models.PositiveIntegerField()
    expira_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name_prod

# Modelo Pedidos
class Pedido(models.Model):
    id_ped = models.AutoField(primary_key=True)
    participante = models.ForeignKey('Participantes', on_delete=models.CASCADE)
    product = models.ForeignKey('Productos', on_delete=models.CASCADE)
    cantidadp = models.PositiveIntegerField() 
    # se refiere a la cantidad que del producto que se quiere comer cada integrante del equipo
    published_date = models.DateTimeField(
            blank=True, null=True)

    def __str__(self):
        return '%s %s' % (self.id_ped,'Pedido')

comidas/forms.py
from django.forms import ModelForm
from .models import Pedido
from django import forms

class CrearPedidos(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['participante','product', 'cantidadp']

comidas/views.py
from django.shortcuts import render
from django.utils import timezone
from comidas.models import Productos
from comidas.models import Participantes
from comidas.models import Pedido
from comidas.forms import CrearPedidos
from django.shortcuts import render, redirect
from django.db.models import Count, Sum
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from itertools import chain
from django.db.models import Max

# Crear vista para ingresar al sistema
def ingresar(request):
    formulario = AuthenticationForm()
    if request.method == 'POST':
        # Añadimos los datos recibidos al formulario
        formulario = AuthenticationForm(data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data['username']
            clave = formulario.cleaned_data['password']
            # Verificamos las credenciales del usuario
            usr = authenticate(usarname=usuario, password=clave)
            return redirect('pedidos_list')
   
    return render(request, 'pedidos/ingresar.html', {'formulario':formulario})

# Crear vista de cerrar sesión
def logout(request):
    # Finalizamos la sesión
    do_logout(request)
    # Redireccionamos a la portada
    return redirect('ingresar')

# Crear  vista de lista de productos.
def productos_list(request):
    productos = Productos.objects.order_by('name_prod')
    return render(request, 'productos/productos_list.html', {'productos': productos})

# Crear  vista de lista de pedidos.
def pedidos_list(request):
    pedidos = Pedido.objects.order_by('id_ped')
    return render(request, 'pedidos/pedidos_list.html', {'pedidos': pedidos})

# Crear vista de crear un pedido.
def pedido_new(request):

    # condicion para crear formulario vacio
    if request.method == "POST":
        form = CrearPedidos(request.POST)
        # condicion para validar formulario
        if form.is_valid():
            cpedido = form.save(commit=False)
            cpedido.auth = request.user
            cpedido.published_date = timezone.now()
            cpedido.product = form.cleaned_data['product']
            cpedido.cantidadp = form.cleaned_data['cantidadp']
            # producto = Productos.objects.values('cantidad')
            # cpedido.cantidadp = F(cantidad) - F(cpedido.cantidadp)
            # producto.save()
            # cantidadp.save()
            cpedido.save()
            return redirect('productos_list')
    else:
        form = CrearPedidos()

    return render(request, 'pedidos/add.html', {'form': form})

# Crear vista del miembro del equipo que consume mas
def come_part(request):
    # se muestra los valores de la relacion participantes pedido se lo anota y se suma la cantidad de productos que ha consumido se ordena por la suma y se obtiene el primero
    comidas = Pedido.objects.values('participante__first_name').annotate(sum=Sum('cantidadp')).order_by('-sum').first()
    return render(request, 'pedidos/come_part.html', {'comidas': comidas})

# Crear vista del miembro del equipo que consume mas
def come_prod(request):
    # se muestra los valores de la relacion productos pedido se lo anota y se suma la cantidad de productos consumidos y luego se muestra el que mas se consumio
    producto = Pedido.objects.values('product__name_prod').annotate(sum=Sum('cantidadp')).order_by('-sum').first()
    return render(request, 'pedidos/come_prod.html', {'producto': producto})

comidas/templates/pedidos/add.html
{% extends 'productos/base.html' %}

{% block header %}
<div class="row session">
    <h3>Bienvenido <i class="fas fa-user"></i></h3>
    <a href="{% url 'ingresar' %}">Cerrar sesión</a>
</div>
{% endblock %}

{% block content %}
<div class="content-body">
	<h2>Agregar consumo</h2>
    <form method="POST" class="post-form">
    	{% csrf_token %}
    	<div class="form-group col-md-3">
            <label for="id_participante">Participante:</label>
            {{ form.participante }}
        </div>
        <div class="form-group col-md-4">
            <label for="id_product">Producto a consumir:</label>
            {{ form.product }}
        </div>
        <div class="form-group col-md-5">
            <label for="id_cantidadp">Cantidad a consumir:</label>
            {{ form.cantidadp }}
        </div>
        <div class="fila">
	        <a href="{% url 'productos_list' %}" class="btn btn-default btn-add">Cancelar</a>
            <button type="submit" class="btn btn-default btn-add">Guardar</button>
        </div>
    </form>
</div>
{% endblock %}

comidas/templates/pedidos/come_part.html
{% extends 'productos/base.html' %}

{% block header %}
<div class="row session">
    <h3>Bienvenido <i class="fas fa-user"></i></h3>
    <a href="{% url 'ingresar' %}">Cerrar sesión</a>
</div>
{% endblock %}

{% block content %}
<div class="content-body">

    <h2>Miembro del equipo que consume más</h2>

    <div class="row fila letter">
        <label class="col-md-2">Nombre </label>
        <label class="col-md-5">Productos Consumidos </label>
    </div>
    <div class="row fila letter">
        <p class="col-md-2"> {{ comidas.participante__first_name }}</p>
        <p class="col-md-2">{{ comidas.sum }}</p>
    </div>
    <br>
    <div class="row">
        <a href="{% url 'pedido_new' %}" class="top-menu"> Agregar Consumo <span class="glyphicon glyphicon-plus"> | </span></a>
        <a href="{% url 'productos_list' %}" class="top-menu"> Ver Productos <span class="glyphicon glyphicon-th-list"> | </span></a>
        <a href="{% url 'pedidos_list' %}" class="top-menu"> Ver Consumos <span class="glyphicon glyphicon-th-list"> | </span></a>
        <a href="{% url 'come_prod' %}" class="top-menu"> Producto más consumido <span class="glyphicon glyphicon-certificate"></span></a>
    </div>
</div>
{% endblock %}

comidas/templates/pedidos/come_prod.html
{% extends 'productos/base.html' %}

{% block header %}
<div class="row session">
    <h3>Bienvenido <i class="fas fa-user"></i></h3>
    <a href="{% url 'ingresar' %}">Cerrar sesión</a>
</div>
{% endblock %}

{% block content %}
<div class="content-body">
    
    <h2>Producto que se consume más</h2>

    <div class="row fila letter">
        <label class="col-md-3">Producto </label>
        <label class="col-md-5">Unidades Consumidas </label>
    </div>
    <div class="row fila letter">
        <p class="col-md-3"> {{ producto.product__name_prod }}</p>
        <p class="col-md-2">{{ producto.sum }}</p>
    </div>
    <br>
    <div class="row">
        <a href="{% url 'pedido_new' %}" class="top-menu"> Agregar Consumo <span class="glyphicon glyphicon-plus"> | </span></a>
        <a href="{% url 'productos_list' %}" class="top-menu"> Ver Productos <span class="glyphicon glyphicon-th-list"> | </span></a>
        <a href="{% url 'pedidos_list' %}" class="top-menu"> Ver Consumos <span class="glyphicon glyphicon-th-list"> | </span></a>
        <a href="{% url 'come_part' %}" class="top-menu"> Quién come más? <span class="glyphicon glyphicon-user"></span></a>
    </div>
</div>
{% endblock %}

comidas/templates/pedidos/ingresar.html
{% extends 'productos/base.html' %}

{% block content %}
<div class="login-form">
    <h2>Login Comida Monoku</h2>
    <h4>Por favor inicia sesión</h4>
    <form id=formulario method="POST" action='' class="post-form">
        {% csrf_token %}
        {{ formulario.non_field_errors }}
        <div class="login-form-group">
            <label for="id_username">Usuario:</label>
            <div class="group">
                <i class="fas fa-user"></i>
                {{ formulario.username }}
            </div>
        </div>
        <div class="login-form-group">
            <label for="id_password">Contraseña:</label>
            <div class="group">
                <i class="fas fa-unlock"></i>
                {{ formulario.password }}
            </div>
        </div>
        <button type="submit">Ingresar</button>
    </form>
</div>
{% endblock %}

comidas/templates/pedidos/pedidos_list.html
{% extends 'productos/base.html' %}

{% block header %}
<div class="row session">
    <h3>Bienvenido <i class="fas fa-user"></i></h3>
    <a href="{% url 'ingresar' %}">Cerrar sesión</a>
</div>
{% endblock %}

{% block content %}
<div class="content-body">
    
    <h2>Lista de Consumos</h2>
    
    {% for pedido in pedidos %}
        <div class="row fila">
            <div class="col-md-2">
                <label> {{ pedido }}: </label>
                |
            </div>
            <div class="col-md-8">
                <p>Quién consume: {{ pedido.participante }}  |  Producto: {{ pedido.product }} |  Cantidad: {{ pedido.cantidadp }}</p>
            </div>
        </div>
    {% endfor %}
    <br>
    <div class="row">
        <a href="{% url 'pedido_new' %}" class="top-menu"> Agregar Consumo <span class="glyphicon glyphicon-plus"> | </span></a>
        <a href="{% url 'productos_list' %}" class="top-menu"> Ver Productos <span class="glyphicon glyphicon-th-list"> | </span></a>
        <a href="{% url 'come_part' %}" class="top-menu"> Quién come más? <span class="glyphicon glyphicon-user"> | </span></a>
        <a href="{% url 'come_prod' %}" class="top-menu"> Producto más consumido <span class="glyphicon glyphicon-certificate"></span></a>
    </div>
</div>
{% endblock %}

comidas/templates/productos/base.html
{% load static %}
<html>
    <head>
        <title>Comidas Monoku</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/comidas.css' %}">

        <script src="https://kit.fontawesome.com/6e60ddec9a.js"></script>
        <!-- <link href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet"/> -->

        <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    </head>
        <div class="page-header">
            <h1>Comida Monoku</h1>
            {% block header %}
            {% endblock %}
        </div>
<body>
    <div class="content container">
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <div class="col-md-12" style="text-align: center;">
        <br>
        <p>MONOKU - We Go Beyond</p>
        <br>
        </div>
    </footer>
</body>
</html>

comidas/templates/productos/productos_list.html
{% extends 'productos/base.html' %}

{% block header %}
<div class="row session">
    <h3>Bienvenido <i class="fas fa-user"></i></h3>
    <a href="{% url 'ingresar' %}">Cerrar sesión</a>
</div>
{% endblock %}

{% block content %}
<div class="content-body">

    <h2>Lista de Productos</h2>

    {% for producto in productos %}
        <div class="row fila">
            <div class="col-md-3">
                <label> {{ producto }}: </label>
                |
            </div>
            <div class="col-md-8">
                <p> Cantidad: {{ producto.cantidad }}  |  Expira: {{ producto.expira_date }} </p>
            </div>
        </div>
    {% endfor %}
    <br>
    <div class="row">
        <a href="{% url 'pedido_new' %}" class="top-menu"> Agregar Consumo <span class="glyphicon glyphicon-plus"> | </span></a>
        <a href="{% url 'pedidos_list' %}" class="top-menu"> Ver Consumos <span class="glyphicon glyphicon-th-list"> | </span></a>
        <a href="{% url 'come_part' %}" class="top-menu"> Quién come más? <span class="glyphicon glyphicon-user"> | </span></a>
        <a href="{% url 'come_prod' %}" class="top-menu"> Producto más consumido <span class="glyphicon glyphicon-certificate"></span></a>
    </div>
</div>
{% endblock %}